### PR TITLE
bug(Makefile) fixes issue #130

### LINKED ISSUE #130: make clean package results in error due to GH_ORG and GOLANGCI_LINT_BINARY
**Describe the bug**

Running `make clean package` results in errors due to unecessary GH_ORG environment variable and also GOLANGCI_LINT_BINARY not being set properly when GOPATH has many entries

**To Reproduce**

1. Get latest version of appsody code
2. run `make clean package`
3. First you get error for GOLANGCI_LINT_BINARY
4. Later you get issues when it tries to download controller unless GH_ORG is set

Assumes `GH_ORG` is not an environment variable and `GOPATH` has many entries in it, e.g., `/Users/maximilien/Desktop/github/appsody:/Users/maximilien/go` or `/Users/maximilien/go:/Users/maximilien/Desktop/github/appsody`

**Expected behavior**

Completed build.

**Actual behaviour**

Two errors:

1. due to GOLANGCI_LINT_BINARY

```bash
➜  appsody git:(master) ✗ make clean package
Makefile:47: *** target pattern contains no `%'.  Stop
```

2. due to GH_ORG

```bash
➜  appsody git:(master) ✗ make clean package
rm -rf /Users/maximilien/Desktop/github/appsody/src/github.com/appsody/appsody/build
rm -rf /Users/maximilien/Desktop/github/appsody/src/github.com/appsody/appsody/package
rm -f O_PATH/bin/golangci-lint
go clean
# make docs md file
mkdir my-project

...
# many many lines of output

./debian/control
--2019-07-30 01:18:03--  https://github.com//controller/releases/download/0.2.2/appsody-controller
Resolving github.com (github.com)... 192.30.253.112
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-07-30 01:18:04 ERROR 404: Not Found.
```

**Environment Details (please complete the following information):**

Mac OS X

**If applicable please specify:**

N/A 

**Screenshots**

N/A

**Additional context**

Golang setup

```bash
➜  appsody git:(master) ✗ echo $GOPATH
/Users/maximilien/go:/Users/maximilien/Desktop/github/appsody
➜  appsody git:(master) ✗ go version
go version go1.12.7 darwin/amd6
```

### PR DESCRIPTION
**Pull request by maximilien**
Fixes #130 

* GO_PATH usage in Makefile should allow `GOPATH` with multiple entries

### CODE REVIEW

**Comment by chilanti** [comment]
Also - in order to have `make` commands run successfully locally, you need to `export GH_ORG=appsody` (or set it to whatever account your repositories reside). Thanks.

**Comment by maximilien** [comment]
OK, thanks for the explanation. Thinking two possible ways to help newbies like me:

1. add `GH_ORG := appsody` in the `Makefile` which means you will have to fix your test to change that...

2. Add a small note on top of the README since could not see any note of setting `GH_ORG` in the docs.

Let me know and I will make changes. I am also looking at other parts. Might have questions and will ask on Slack first. Cheers :beers:

**Comment by chilanti** [comment]
@maximilien - the reason why we left GH_ORG outside Makefile is that - otherwise - we would have to be careful with checking in the Makefile from our repos when we commit/push. Say I am testing - I'd have to set GH_ORG to `chilanti`. But then, I'd have to revert that to `appsody` before I check in my code, because otherwise that change would go into the PR. So - to avoid that... we made it a repo variable. The fact that it isn't documented is another true statement - so, if you agree, I'll create an issue to have the manual build/deploy properly documented (other people are running into problems). Let me know what  you think.

**Comment by maximilien** [comment]
@chilanti sounds good. I’ll remove my changes to GH_ORG here.

**Comment by maximilien** [comment]
Done @chilanti

**Comment by henrynash** [comment]
Just an idea...why don't we test to see if GH_ORG is not set in the makefile, and if so, set it to "appsody"? That way you could override it by setting it in the environment before running them make if you need to.

**Comment by maximilien** [comment]
> Just an idea...why don't we test to see if GH_ORG is not set in the makefile, and if so, set it to "appsody"? That way you could override it by setting it in the environment before running them make if you need to.

I'd be OK with that too.

@chilanti any opinions?

**Comment by kewegner** [comment]
The GH_ORG issue has been addressed.

**Pull request closed without merging**
