### PR TITLE
Remove global vars and init() functions

### LINKED ISSUE #378: Remove global variables and init() functions
This is a critical step in refactoring our CLI code to reduce bugs, improve testability, and improve maintainability.

The globals were conflicting and overwriting each other in cases of multiple threads, and it was getting very tough for developers to know the proper scope of variables.

This will set us up for code coverage in automated tests, reorganizing the code in multiple packages, and modularizing the code into proper objects.

### PR DESCRIPTION
**Pull request by kylegc**
Fixes #378 

I've managed to remove all the global vars and init() functions. It isn't pretty, sorry for the large PR, but it is necessary. For now it is mostly passing around config structs as method parameters, but in the future I hope to continue refactoring this into proper objects.

### CODE REVIEW

**Comment by Kamran64** [comment]
Commands tested:
- [ ]
- [ ]
- [ ]
- [ ]

**Comment by Kamran64** [comment]
Making a list of commands tested and code checked. Feel free to tick off (or add any I may have missed out on)

Commands tested:
- [ ] ```appsody init```
- [ ] ```appsody run```
- [ ] ```appsody test```
- [ ] ```appsody debug```
- [ ] ```appsody build```
- [ ] ```appsody deploy```
- [ ] ```appsody repo``` commands
- [ ] ```appsody list```
- [ ] ``` appsody ps```
- [ ] ```appsody stack``` commands

Misc:
- [ ] Utils files

**Comment by skoh7645** [comment]
To add on from @Kamran64's comment:
- [ ] ``` appsody completion``` 
- [ ] ``` appsody extract``` 
- [ ] ``` appsody operator``` 
- [ ] ``` appsody completion``` 
- [ ] ``` appsody stop``` 
- [ ] ``` appsody version```

**Comment by skoh7645** [comment]
Sorry @kylegc, you will have to revert my merge as I accidentally removed the changes implemented in this commit https://github.com/appsody/appsody/commit/6fe994573a17d376c9e0b229d2ff70cb95243434

**Comment by kylegc** [comment]
I tested the command structure by generating the cli-commands.md doc and comparing it with the last version in the website. 
There were no changes to the command structure, only a small change to remove the path slug at the top which I fixed.

**Comment by kewegner** [comment]
Merging, with concurrence of team.

**Pull request merged**
