### PR TITLE
Update the linter to check for custom template variables and other misc fixes

### PR DESCRIPTION
**Pull request by Kamran64**
Fixes: https://github.com/appsody/appsody/issues/625
Fixes: https://github.com/appsody/appsody/issues/626

- Checks that custom templating variables have been used in the stack. If not, the user will be warned. If they have, and the the keys or values do not match an alphanumeric format, the Linter will throw an error.

- Removes the struct defined in the `stack_yaml_lint.go` to use the `stack_package.go` struct

- Removes the function to check for the default template. This has now been achieved by adding a field to the struct (which for some reason wasn't working previously!)

- Adds a function to `utils.go` to check the input meets the format for semver (And removes the existing version check function in the Linter)

### CODE REVIEW

**Comment by kylegc** [comment]
@Kamran64 Please resolve the merge conflicts in this PR. Thanks

**Comment by Kamran64** [comment]
@kylegc - Resolved :)

**Comment by Kamran64** [comment]
Sorry @kylegc - I've just had to fix a few more merge conflicts since there's been a few changes to these files in the past week and my PR rewrites a couple of stuff. Should be ready for review now thanks.

**Comment by BarDweller** [comment]
why are custom template values limited to alphanumeric regex? won't this break the planned version range value I'm using over in 517/529 (stacks repo prs)?

**Comment by Kamran64** [comment]
Thanks @BarDweller - You're right. I just fixed this so that the check is only enforced on keys and not values.

**Pull request merged**
