### PR TITLE
sorted appsody list command alphabetically by repo and stack list

### PR DESCRIPTION
**Pull request by Kamran64**
```appsody list``` and ```appsody repo list``` commands are now sorted alphabetically by repo list followed by stack list.

Fixes: https://github.com/appsody/appsody/issues/151

### CODE REVIEW

**Comment by Kamran64** [comment]
1. Sorting out the lint errors now.

2. I opted to use the sort package initially but was struggling to apply it to the stack/repo table. Also tried throwing all the data into a 2D array and then using the package but had similar issues. I would be open to finding a more efficient fix though.

3. I agree with this also. Is there any way I can set the array size to be variable? (Sorry, Go beginner here)

**Comment by kewegner** [comment]
Re: #1 thanks
Re: #2, OK for this release lets see if we can get the code in as is, and look at improvements in the next sprint.  
Re: #3, maybe you could use append to dynamically re-size.

**Comment by kewegner** [comment]
I added your changes into my local copy of repo.go

I think I know why build is failing, there is a test that expects the experimental repo to be there, which it should be.  The test that is failing does an appsody list, but as you can see nothing is listed.  If I add the repo name then things get listed.  The test is looking for nodejs and java-microprofile (It also adds a local repo from a .yaml file named incubatortest)

'appsody list' should list all projects from all repos

sesadmins-MacBook-Pro:build sesadmin$ appsody list

REPO	ID	VERSION	DESCRIPTION
sesadmins-MacBook-Pro:build sesadmin$ appsody list appsodyhub

REPO      	ID               	VERSION	DESCRIPTION                                
appsodyhub	java-microprofile	0.2.4  	Eclipse MicroProfile using OpenJ9 and Maven
appsodyhub	java-spring-boot2	0.3.2  	Spring Boot using OpenJ9 and Maven         
appsodyhub	nodejs-express   	0.2.2  	Express web framework for Node.js          
appsodyhub	nodejs           	0.2.2  	Runtime for Node.js applications           
appsodyhub	swift            	0.1.0  	Runtime for Swift applications             
sesadmins-MacBook-Pro:build sesadmin$ appsody list experimental

REPO        	ID              	VERSION	DESCRIPTION                                  
experimental	nodejs-functions	0.1.0  	Serverless runtime for Node.js functions     
experimental	quarkus         	0.1.0  	Quarkus runtime for running Java applications

**Comment by kewegner** [comment]
I got the code working with sort and slices.  Lets talk Thursday, and see if it looks better to you.
I got both repos and repo/stacks sorted alphabetically.

**Pull request merged**
