### PR TITLE
Cache and reuse the results of getEnvVar()

### PR DESCRIPTION
**Pull request by pushkarnk**
Motivation:
Commands may call getEnvVar() multiple times for different environment
variable names. Every invocation needs a `docker inspect` invocation followed
by unmarshalling of the json and a walk through the resulting array. Caching
the environment variables in a map can avoid repeating these steps and speed-up
command execution.

### CODE REVIEW

**Comment by pushkarnk** [comment]
cc @gireeshpunathil

**Comment by gireeshpunathil** [comment]
LGTM! this also solves the issue of too many logging of environment variables (right now it prints the whole list per invocation of this API) and restrict it to once per CLI invocation.

**Comment by chilanti** [comment]
Hi Pushkar - thanks for the PR - can I ask you to open an issue and associate it with the PR? We are trying to get every PR associated w/ an issue. Also - opening an issue in advance would help us with planning (and is likely to prevent some duplication of work). Thanks.

**Comment by pushkarnk** [comment]
@chilanti Created #335

**Comment by pushkarnk** [comment]
Moved the cache from being a global var, into RootCommandConfig.

**Pull request merged**
