### PR TITLE
Ensure consistent labels in image and app-deploy

### PR DESCRIPTION
**Pull request by EnriqueL8**
Currently the `created` label from the image build and the `app-deploy.yaml` are not matching because we compute the labels twice. In this PR, I cache the labels inside the `RootCommandConfig`. I thought of packaging up the labels into a struct, but it could be the case that a function will be used independently - would like to hear thoughts on this!

### CODE REVIEW

**Comment by kylegc** [comment]
First, good catch on this! The labels should definitely be reused and consistent between the build image and the app-deploy.yaml.

For the implementation, caching then in the `RootCommandConfig` works, but I think I prefer a simpler solution. Since the "cache" only needs to happen in the build command, we can simply call `getLabels()` once and then pass the `labels` map as a parameter to `updateDeploymentConfig()`. This we we don't impact the root config for everyone.
What do you think?

**Comment by EnriqueL8** [comment]
okay - sounds good I can modify that. I was just following that approach because we already cache the stack labels.

**Comment by kylegc** [comment]
Do you remember why we added the `cachedStackLabels`? Looks like it is only being called once so the cache isn't used.

**Comment by kylegc** [comment]
@EnriqueL8 I think this looks good, but the build is failing. Please rebase this on top of PR #711 so you can take advantage of the new test sandboxing.

**Comment by EnriqueL8** [comment]
I have rebased this change on top of the test sandboxing PR

**Pull request merged**
