### PR TITLE
cmd: harden `--docker-options` parsing

### PR DESCRIPTION
**Pull request by gireeshpunathil**
~~Disallow anything that does not start with a `-`.
(luckily all the docker run options do)~~

EDIT: As per discussion, this was not pursued due to maintenance overhead.

Disallow `--help`
(not the best place to do `docker run --help`)
(in addition, even if it is, the output is truncated, so!)

Fixes: https://github.com/appsody/appsody/issues/346

cc @kylegc @chilanti @kewegner

### CODE REVIEW

**Comment by kewegner** [comment]
I think the change for --help is ok, I am not sure ^[^-].*)| is good though.  The reason is it is checking the whole string, not just the options so for instance if I have -m 4g  will this work if the regex runs against the '4g'.  I will test this out and get back to you.

**Comment by gireeshpunathil** [comment]
@kewegner - I see! let me play around with regex a bit and see if there is a way; and meanwhile let use see what others think about this.

**Comment by gireeshpunathil** [comment]
per conversation in the tracking issue, I will go just with blacklisting `--help` (makes sense to do, easy to do, good to do as its o/p is truncated atm)

**Comment by gireeshpunathil** [comment]
adjusted the changes accordingly, @kewegner , @kylegc - ptal.

**Pull request merged**
