### PR TITLE
Print quoted and escaped command args for copying

### PR DESCRIPTION
**Pull request by kylegc**
We log a lot of commands to the terminal which users can copy and paste and run themselves. However some of these commands cannot directly run with copy and paste, they need editing to add quotes or escape characters.

The PR attempts to print ready-to-copy commands to the terminal so users don't get confused when copied commands don't work.

See also https://appsody.slack.com/archives/CKXDDB4A3/p1580859781018200

### CODE REVIEW

**Comment by kylegc** [comment]
Travis is failing on test TestStackCreateInvalidStackCase2. This test is failing for me locally on master too. Maybe PR #870  will fix this?

**Comment by kylegc** [comment]
Looks like the test failure is being worked on here #890

**Comment by EnriqueL8** [comment]
Yup, had a quick look - will need further investigation!

**Comment by EnriqueL8** [comment]
@kylegc could you rebase this PR and resolve the conflicts? Thanks!!

**Comment by kylegc** [comment]
> @kylegc could you rebase this PR and resolve the conflicts? Thanks!!

Done

**Comment by EnriqueL8** [comment]
@neeraj-laad we could use this funciton for #591

**Pull request merged**
